### ISSUE TITLE
Cannot connect to dashboard.

### ISSUE THREAD

**Issue by itach11** [SAP-samples/teched2020-DEV269#3] opened 2020-12-15 16:44 UTC
Hello,
I'm struggling to complete exercise  2.2. I downloaded the Kubeconfig and ran the kubectl  proxy command but 
I'm using GCP as a provider the cluster name is : qexc9xun
Any ideas? 
 ## Which cluster is affected?
 
`Link`: [abyss/qexc9xun](https://gardener.ing.teched.gardener.cloud.sap/namespace/garden-abyss/shoots/qexc9xun/)
 
## What happened?
 I'm trying to connect to the Kubernetes dashboard. However, I get 403 code and the following message : 
```
"services \"https:kubernetes-dashboard:\" is forbidden: User \"system:cluster-admin\" cannot get resource \"services/proxy\" in API group \"\" in the namespace \"kubernetes-dashboard\""
```  
## What you expected to happen?
 To be able to connect successfully.
## When did it happen or started to happen?
`Timestamp`: 2020-12-15T16:38:06Z
 
## Anything else we need to know?

**Comment by petersutter** [comment] 2020-12-15 18:12
Hi @itach11, thanks for reporting. I could reproduce your issue when running `kubectl proxy`. This may be due to the limited permissions that are assigned to `cluster-admin` for the exercise clusters, as indicated in the exercises:

>NOTE: With the downloaded kubeconfig you only have the permission to read and delete resources in your cluster. You can't create or update resources (like deployments). This restriction only applies for this workshop.*

cc @rfranzke can you take a look?

The kubernetes dashboard is not part of the exercise, that's probably why we didn't notice this issue when running through the exercise. However, you should be able to complete exercise 2.2 using `kubectl` only

**Comment by petersutter** [comment] 2020-12-16 09:54
Hi @itach11, we made a fix for the kubernetes dashboard issue that we will soon deploy so that you will be able to login and have at least a read only view on the kubernetes dashbaord (teched environment restriction)

**Comment by petersutter** [comment] 2020-12-16 10:10
I have triggered a reconcile for your cluster. It works now

**Closed by petersutter** 2020-12-16 10:10 UTC
